export default {
  fonts: {
    body: 'system-ui, sans-serif',
    heading: '"Avenir Next", sans-serif',
    monospace: 'Menlo, monospace',
    headText:  '"Avenir Next", sans-serif',
    normalText:'Montserrat,-apple-system, BlinkMacSystemFont, "San Francisco", "Helvetica Neue", Helvetica, Ubuntu, Roboto, Noto, "Segoe UI", Arial, sans-serif',
    numberInput:'DIN Alternate'
  },
  colors: {
    white: '#fff',

    text: '#0d0d0d',
    background: '#fff',
    primary: '#05A447',
    title_background_top: '#b4b4b4',
    title_background_bottom: '#C6C7C8',
    title_box_shadow: '#0000000f',
    normal_button_bg:'#D5D6D580',
    normal_button_active:'#3F3E3E',
    toggle_button_bg:'#6d6d6d',
    toggle_button_active:'#888888',
    text_input_bg:'#9999994d',
    text_input_text:'#0D0D0D80',
    text_input_border:'#0D0D0D10',
    range_input_thumb:'#343434',
    range_input_thumb_active:'#33a852',
    range_input_thumb_unactive:'#D1D6D1',
    main_top_bg:'#F9FBF9',
    main_bottom_bg:'#FFFFFF',
    adb_background:'#EDEFEE',
    adb_border:'#DBDBDB',
    modes:{
      dark:{
        text: '#fff',
        background: '#000',
        primary: '#77FBAD',
        title_background_top: '#464849',
        title_background_bottom: '#38393A',
        title_box_shadow: '#ffffff1a',
        normal_button_bg:'#70717280',
        normal_button_active:'#CECDCD',
        toggle_button_bg:'#a0a0a0',
        toggle_button_active:'#888888',
        text_input_bg:'#9999994d',
        text_input_text:'#FFFFFF80',
        text_input_border:'#FFFFFF10',
        range_input_thumb:'#CCCBCC',
        range_input_thumb_active:'#77FBAD',
        range_input_thumb_unactive:'#3E4140',
        main_top_bg:'#141615',
        main_bottom_bg:'#030303',
        adb_background:'#131614',
        adb_border:'#242424',
      },
      splash:{
        title_background_top: '#46484900',
        title_background_bottom: '#38393A00',
        title_box_shadow: '#00000000',
      }
    }
  },
}